webtalk_init -webtalk_dir C:/Users/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.sim/sim_1/behav/xsim/xsim.dir/WS2812_FEED_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov 21 19:24:01 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "208bb027-3bf6-45b4-8485-1891602b329c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "20284ac54ea34f73831e45d01022907a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4000001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6316_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3197199328 -regid "" -xml C:/Users/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.sim/sim_1/behav/xsim/xsim.dir/WS2812_FEED_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.sim/sim_1/behav/xsim/xsim.dir/WS2812_FEED_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.sim/sim_1/behav/xsim/xsim.dir/WS2812_FEED_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
