# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {IP_Flow 19-4995}  -suppress 
set_msg_config  -id {IP_Flow 19-2207}  -suppress 
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {VRFC 10-718}  -suppress 
set_msg_config  -severity {WARNING}  -suppress 
set_msg_config  -id {XSIM 43-3321}  -string {{ERROR: [XSIM 43-3321] Static elaboration of top level VHDL design unit simulation in library work failed.}}  -suppress 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.cache/wt [current_project]
set_property parent.project_path /home/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths /home/wilson/Documents/Project/my_w2812b_Project/ip_repo/myW2812bDesignIP_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/wilson/Documents/Project/my_w2812b_Project/W2812b_HW_Design/W2812b_HW_Design.srcs/sources_1/new/WS2812_controller.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top WS2812_controller -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef WS2812_controller.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file WS2812_controller_utilization_synth.rpt -pb WS2812_controller_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
