# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/W2812b_design_1/W2812b_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1 || ORIG_REF_NAME==W2812b_design_1} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_processing_system7_0_0/W2812b_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_processing_system7_0_0 || ORIG_REF_NAME==W2812b_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_ps7_0_axi_periph_0/W2812b_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==W2812b_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_rst_ps7_0_100M_0/W2812b_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==W2812b_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_xbar_0/W2812b_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_xbar_0 || ORIG_REF_NAME==W2812b_design_1_xbar_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_axi_gpio_0_0/W2812b_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_axi_gpio_0_0 || ORIG_REF_NAME==W2812b_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_myW2812bDesignIP_0_1/W2812b_design_1_myW2812bDesignIP_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_myW2812bDesignIP_0_1 || ORIG_REF_NAME==W2812b_design_1_myW2812bDesignIP_0_1} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_myW2812bDesignIP_1_0/W2812b_design_1_myW2812bDesignIP_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_myW2812bDesignIP_1_0 || ORIG_REF_NAME==W2812b_design_1_myW2812bDesignIP_1_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_myW2812bDesignIP_2_0/W2812b_design_1_myW2812bDesignIP_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_myW2812bDesignIP_2_0 || ORIG_REF_NAME==W2812b_design_1_myW2812bDesignIP_2_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_myW2812bDesignIP_3_0/W2812b_design_1_myW2812bDesignIP_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_myW2812bDesignIP_3_0 || ORIG_REF_NAME==W2812b_design_1_myW2812bDesignIP_3_0} -quiet] -quiet

# IP: bd/W2812b_design_1/ip/W2812b_design_1_auto_pc_0/W2812b_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2812b_design_1_auto_pc_0 || ORIG_REF_NAME==W2812b_design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_processing_system7_0_0/W2812b_design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==W2812b_design_1_processing_system7_0_0 || ORIG_REF_NAME==W2812b_design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_rst_ps7_0_100M_0/W2812b_design_1_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==W2812b_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==W2812b_design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_rst_ps7_0_100M_0/W2812b_design_1_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==W2812b_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==W2812b_design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_xbar_0/W2812b_design_1_xbar_0_ooc.xdc

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_axi_gpio_0_0/W2812b_design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==W2812b_design_1_axi_gpio_0_0 || ORIG_REF_NAME==W2812b_design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_axi_gpio_0_0/W2812b_design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_axi_gpio_0_0/W2812b_design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==W2812b_design_1_axi_gpio_0_0 || ORIG_REF_NAME==W2812b_design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/W2812b_design_1/ip/W2812b_design_1_auto_pc_0/W2812b_design_1_auto_pc_0_ooc.xdc

# XDC: bd/W2812b_design_1/W2812b_design_1_ooc.xdc
